language: android
sudo: false
jdk:
- oraclejdk8
branches:
#- master
- feature-travis_test
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - android-23
  - android-22
  - android-24
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-22
  - extra-android-support
script:
- "./travis_script.sh eyeseetea hnqis"
#- "./gradlew testEyeseeteaDebugUnitTest -i"
#- "./gradlew testHnqisDebugUnitTest -i"
# insturmental tests
#- ./gradlew testEyeseeteaDebugTest -i
#- ./gradlew testHnqisDebugTest -i
before_script:
- "./travis_before_script.sh"
notifications:
  slack:
    secure: V8Wxde5RTNbNiOzulv6idvMpbWtjVc4DPwApjAgfDI01OD6nLkuogr/z3qqyKbA/uwWnzu5g7+vegFtSdjW1z32kiIO0bO2c0m2L/E542D1/zmWT9N0IPghQIZ+9BAj1ZrgG286tiX85lSV8uLy0r9bAefPWlbdrHhirYi3cTsI=
  email: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
